In [ ]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
df_home = pd.read_csv("C:/Users/lenovo/Desktop/EcoGuardian/data/energy_dataset.csv")

In [ ]:
print(f"Dataset shape: {df_home.shape}")
print(f"\nColumns: {list(df_home.columns)}")
print(f"\nFirst few rows:")
df_home.head()

Dataset shape: (100000, 8)

Columns: ['Home ID', 'Appliance Type', 'Energy Consumption (kWh)', 'Time', 'Date', 'Outdoor Temperature (°C)', 'Season', 'Household Size']

First few rows:

,Home ID,Appliance Type,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Season,Household Size
0,94,Fridge,0.20,21:12,2023-12-02,-1.0,Fall,2
1,435,Oven,0.23,20:11,2023-08-06,31.1,Summer,5
2,466,Dishwasher,0.32,06:39,2023-11-21,21.3,Fall,3
3,496,Heater,3.92,21:56,2023-01-21,-4.2,Winter,1
4,137,Microwave,0.44,04:31,2023-08-26,34.5,Summer,5

In [ ]:
# Data exploration and preprocessing
print("Dataset Info:")
df_home.info()

print("\nMissing values:")
print(df_home.isnull().sum())

print("\nStatistical summary:")
df_home.describe()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Home ID                   100000 non-null  int64
 1   Appliance Type            100000 non-null  object
 2   Energy Consumption (kWh)  100000 non-null  float64
 3   Time                      100000 non-null  object
 4   Date                      100000 non-null  object
 5   Outdoor Temperature (°C)  100000 non-null  float64
 6   Season                    100000 non-null  object
 7   Household Size            100000 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 6.1+ MB

Missing values:
Home ID                     0
Appliance Type              0
Energy Consumption (kWh)    0
Time                        0
Date                        0
Outdoor Temperature (°C)    0
Season                      0
Household Size              0
dtype: int64

Statistical summary:

,Home ID,Energy Consumption (kWh),Outdoor Temperature (°C),Household Size
count,100000.000000,100000.000000,100000.000000,100000.000000
mean,250.374980,1.499952,14.950135,3.001770
std,144.435367,1.181176,14.438755,1.417077
min,1.000000,0.100000,-10.000000,1.000000
25%,125.000000,0.590000,2.400000,2.000000
50%,250.000000,1.230000,14.900000,3.000000
75%,375.000000,1.870000,27.400000,4.000000
max,500.000000,5.000000,40.000000,5.000000

In [ ]:
df_home["Date"] = pd.to_datetime(df_home["Date"], errors="coerce") 
df_home["Time"] = pd.to_datetime(df_home["Time"], errors="coerce").dt.time

C:\Users\lenovo\AppData\Local\Temp\ipykernel_17344\2906723350.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_home["Time"] = pd.to_datetime(df_home["Time"], errors="coerce").dt.time

In [ ]:
df_home

,Home ID,Appliance Type,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Season,Household Size
0,94,Fridge,0.20,21:12:00,2023-12-02,-1.0,Fall,2
1,435,Oven,0.23,20:11:00,2023-08-06,31.1,Summer,5
2,466,Dishwasher,0.32,06:39:00,2023-11-21,21.3,Fall,3
3,496,Heater,3.92,21:56:00,2023-01-21,-4.2,Winter,1
4,137,Microwave,0.44,04:31:00,2023-08-26,34.5,Summer,5
...,...,...,...,...,...,...,...,...
99995,124,Microwave,0.42,09:56:00,2023-09-28,20.5,Summer,1
99996,184,Computer,0.71,12:48:00,2023-05-27,-5.4,Spring,2
99997,101,Dishwasher,0.25,05:45:00,2023-02-18,35.6,Winter,3
99998,423,Air Conditioning,2.69,12:39:00,2023-04-20,3.7,Spring,1
99999,429,Fridge,0.37,18:46:00,2023-02-27,36.0,Winter,5

In [ ]:
le = LabelEncoder()
df_home["season_encoded"] = le.fit_transform(df_home["Season"])

In [ ]:
label_encoder = LabelEncoder()
df_home["Appliance_Type_Label"] = label_encoder.fit_transform(df_home["Appliance Type"])
df_home = df_home.drop(columns=["Appliance Type"])

In [ ]:
df_home = df_home.drop(columns=["Season"])
df_home

,Home ID,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Household Size,season_encoded,Appliance_Type_Label
0,94,0.20,21:12:00,2023-12-02,-1.0,2,0,3
1,435,0.23,20:11:00,2023-08-06,31.1,5,2,7
2,466,0.32,06:39:00,2023-11-21,21.3,3,0,2
3,496,3.92,21:56:00,2023-01-21,-4.2,1,3,4
4,137,0.44,04:31:00,2023-08-26,34.5,5,2,6
...,...,...,...,...,...,...,...,...
99995,124,0.42,09:56:00,2023-09-28,20.5,1,2,6
99996,184,0.71,12:48:00,2023-05-27,-5.4,2,1,1
99997,101,0.25,05:45:00,2023-02-18,35.6,3,3,2
99998,423,2.69,12:39:00,2023-04-20,3.7,1,1,0
99999,429,0.37,18:46:00,2023-02-27,36.0,5,3,3

In [ ]:
df_home["Energy Consumption (kWh)"] = pd.to_numeric(df_home["Energy Consumption (kWh)"], errors="coerce") 
df_home["Outdoor Temperature (°C)"] = pd.to_numeric(df_home["Outdoor Temperature (°C)"], errors="coerce") 
df_home["Household Size"] = pd.to_numeric(df_home["Household Size"], errors="coerce")

In [ ]:
df_home = df_home.ffill().bfill()

In [ ]:
#features temporelles
df_home["weekday"] = df_home["Date"].dt.weekday

In [ ]:
df_home = df_home.drop(columns=["hour"])

In [ ]:
df_home.to_csv("C:/Users/lenovo/Desktop/EcoGuardian/data/smart_home_clean.csv", index=False) 
print(" Dataset Smart Home nettoyé et enrichi sauvegardé : smart_home_clean.csv")

 Dataset Smart Home nettoyé et enrichi sauvegardé : smart_home_clean.csv